---
- hosts: mopidy-host
  become: true
  gather_facts: true
  vars:
    soundcard:
      internal_audio: true
      improve_dac: false
      update_firmware: false
    mopidy:
      playlists_dir: "/var/lib/mopidy/playlists"
      media_dir: "/var/lib/mopidy/music"
      user: mopidy
      mpd: 
        enabled: True
        hostname: "::"
        password: ""
      http:
        enabled: False
        # IPv6
        hostname: "::" 
        # IPv4
        # hostname: "0.0.0.0" 
        password: ""
      services:
        - mopidy
    main:
      apt:
        - ntp
        - mopidy
        - python-pip
    extensions:
      apt:
        - mopidy-podcast
        - mopidy-somafm
        - mopidy-tunein
        - mopidy-youtube
        - mopidy-local-sqlite
        - mopidy-alsamixer
    webclients:
      pip:
        - Mopidy-MusicBox-Webclient

  handlers:
    - include: roles/setup/handlers/main.yml 
  roles:
    - mopidy-setup
    - mopidy-setup-extensions
    # - raspbian-soundcard-settings

