- name: add repo key 
  apt_key: url="https://apt.mopidy.com/mopidy.gpg"

- name: add repo
  get_url: dest="/etc/apt/sources.list.d/mopidy.list" url="https://apt.mopidy.com/jessie.list"

- name: update cache and install/upgrade packages
  # cache timeout 1d
  apt: update_cache=yes cache_valid_time=86400 state=latest name="{{ item }}" 
  notify: enable-services
  with_items: "{{ main.apt }}"

- name: pip upgrade pip
  pip:  name=pip state=latest

- name: rollout local config
  template:  src="files/mopidy.conf.j2" dest="/etc/mopidy/mopidy.conf" owner="{{ mopidy.user }}" mode="750"
  notify: restart-services
